server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/news12
    username: root
    password: ok
mybatis:
  mapper-locations: mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true